-- MySQL Script generated by MySQL Workbench
-- Sun Oct  9 14:27:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cst 339 database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cst 339 database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cst 339 database` DEFAULT CHARACTER SET utf8 ;
USE `cst 339 database` ;

-- -----------------------------------------------------
-- Table `cst 339 database`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cst 339 database`.`customers` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(20) NOT NULL,
  `LAST_NAME` VARCHAR(20) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `USERNAME` VARCHAR(30) NOT NULL,
  `Password` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cst 339 database`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cst 339 database`.`order_details` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `OrderNum` INT(11) NOT NULL,
  `Product_ID` INT(11) NOT NULL,
  `Price` DECIMAL(2,2) NOT NULL,
  `Quantity` INT(11) NOT NULL,
  `customers_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `customers_ID`),
  INDEX `fk_order_details_customers_idx` (`customers_ID` ASC),
  CONSTRAINT `fk_order_details_customers`
    FOREIGN KEY (`customers_ID`)
    REFERENCES `cst 339 database`.`customers` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cst 339 database`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cst 339 database`.`products` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NOT NULL,
  `Description` VARCHAR(200) NOT NULL,
  `Price` DECIMAL(5,2) NOT NULL,
  `image_URL` VARCHAR(200) NOT NULL,
  `Quantity` INT(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `cst 339 database`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cst 339 database`.`orders` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Customer_ID` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  `Customer_Address` VARCHAR(100) NOT NULL,
  `Customer_Email` VARCHAR(50) NOT NULL,
  `Order_Date` DATE NOT NULL,
  `order_details_ID` INT(11) NOT NULL,
  `order_details_customers_ID` INT(11) NOT NULL,
  `products_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`, `order_details_ID`, `order_details_customers_ID`, `products_ID`),
  INDEX `fk_orders_order_details1_idx` (`order_details_ID` ASC, `order_details_customers_ID` ASC),
  INDEX `fk_orders_products1_idx` (`products_ID` ASC),
  CONSTRAINT `fk_orders_order_details1`
    FOREIGN KEY (`order_details_ID` , `order_details_customers_ID`)
    REFERENCES `cst 339 database`.`order_details` (`ID` , `customers_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_products1`
    FOREIGN KEY (`products_ID`)
    REFERENCES `cst 339 database`.`products` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
